pub use super::key_snapshot::MODIFIER_CODES;
use crate::config::HotkeyKey;
/// Physical ANSI key positions (Carbon virtual key codes), matching the stored HotkeyKey model.
pub fn code(key: &HotkeyKey) -> u16 {
    use HotkeyKey::*;
    match key {
        ControlLeft => 59,
        ControlRight => 62,
        ShiftLeft => 56,
        ShiftRight => 60,
        AltLeft => 58,
        AltRight => 61,
        MetaLeft => 55,
        MetaRight => 54,
        KeyA => 0,
        KeyS => 1,
        KeyD => 2,
        KeyF => 3,
        KeyH => 4,
        KeyG => 5,
        KeyZ => 6,
        KeyX => 7,
        KeyC => 8,
        KeyV => 9,
        KeyB => 11,
        KeyQ => 12,
        KeyW => 13,
        KeyE => 14,
        KeyR => 15,
        KeyY => 16,
        KeyT => 17,
        KeyO => 31,
        KeyU => 32,
        KeyI => 34,
        KeyP => 35,
        KeyL => 37,
        KeyJ => 38,
        KeyK => 40,
        KeyN => 45,
        KeyM => 46,
        Num1 => 18,
        Num2 => 19,
        Num3 => 20,
        Num4 => 21,
        Num6 => 22,
        Num5 => 23,
        Num9 => 25,
        Num7 => 26,
        Num8 => 28,
        Num0 => 29,
        F1 => 122,
        F2 => 120,
        F3 => 99,
        F4 => 118,
        F5 => 96,
        F6 => 97,
        F7 => 98,
        F8 => 100,
        F9 => 101,
        F10 => 109,
        F11 => 103,
        F12 => 111,
        Space => 49,
        Tab => 48,
        Escape => 53,
        Return => 36,
        Backspace => 51,
        Delete => 117,
        Insert => 114,
        Up => 126,
        Down => 125,
        Left => 123,
        Right => 124,
        Home => 115,
        End => 119,
        PageUp => 116,
        PageDown => 121,
        CapsLock => 57,
    }
}
pub fn strictly_pressed(down: &[u8; 128], keys: &[HotkeyKey]) -> bool {
    super::key_snapshot::pressed(down, &keys.iter().map(code).collect::<Vec<_>>())
}
